### ISSUE TITLE
Deref without array and nullable queries

### ISSUE THREAD

**Issue by olemagnus** [FormidableLabs/groqd#26]
I upgraded to version `0.3` and I'm having some issues recreating a query. `deref()` used to work without `filter()`. I have a reference field that might be empty, and there doesn't seem to be a way to use `nullable()` on on `q()` to handle if there are no references. 

This code worked with `0.2`:
```
role: q(
  "role",
  q.deref(),
  q.grab({
    title: q.string(),
  })
)
```

With `0.3` I get this error: "Property 'deref' does not exist on type 'UnknownQuery'.":
```
role: q("role")
  .deref()
  .grab({ title: q.string() })
```

Adding `filter()` gives me a runtime error because the list can be empty (null):
```
role: q("role").filter().deref().grabOne("title", q.string()),
```

**Comment by gksander** [comment]
Thank you for reporting! This appears to be a regression, but should be an easy fix! I'll try to sneak in a fix here today or early tomorrow.

**Comment by gksander** [comment]
Closing as resolved via #27, released as 0.3.1. Let me know if you're still having issues with this after upgrading to 0.3.1!
